pipeline {

  agent {
    label 'Linux'
  }

  stages {
  
    stage('Build') {
    
      steps {
      
        sh 'mvn -B -DskipTests clean package'
        
      }
      
    }
    
    stage('analyse statique') {
      
      steps {
        
        withSonarQubeEnv('My SonarQube Server') {
          sh "/home/jenkins/bin/sonar-scanner"
        }
        //sh "mvn clean verify sonar:sonar -Dsonar.projectName=test -Dsonar.projectKey=test -Dsonar.projectVersion=${BUILD_NUMBER}";
    
      }
      
    }
    
    stage('Test') {
    
      steps {
      
        sh 'mvn test'
        
      }
      
      post {
      
        always {
        
          junit 'target/surefire-reports/*.xml'
          
        }
        
      }
      
    }
    
    stage ('Publication du binaire') {

      steps {

        script {

          def server = Artifactory.server('Artifactory')
          def uploadSpec = """{
            "files": [
              {
                "pattern": "target/my-app*.jar",
                "target": "Grotadmorv/rondoudou${BUILD_NUMBER}.jar"
              }
            ]
          }"""
          server.upload(uploadSpec)

        }

      }

    }
    
  }
  
}
